name: noted
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
 
  assets:
    - assets/images/cat.jpg
    - assets/images/Dita.jpeg
    - assets/images/Esta.jpeg
    - assets/images/sad-cat.png

  fonts:
    - family: CatPaws
      fonts:
        - asset: assets/fonts/Cat paw.ttf
          weight: 600
    # - family: Cattlya
    #   fonts:
    #     - asset: assets/fonts/Cattlya.ttf
    #       weight: 600